safe:        false
port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: null
markdown:    kramdown
permalink:   pretty

exclude: [CNAME, Gemfile, Gemfile.lock]

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
